name: Auto Update Markdown File with UUID

on:
  push:
    branches:
      - main  # The default branch for your repository
  workflow_dispatch:  # Allows manual triggering of the action

jobs:
  update-markdown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install  # Assuming you may need dependencies for the script

    - name: Run script to update registration.md
      run: node update-registration.js $UUID  # Run your script with UUID as an argument

    - name: Commit and push changes
      run: |
        git config --local user.name "Your Name"
        git config --local user.email "youremail@example.com"
        git add registration.md
        git commit -m "Updated registration with UUID"
        git push origin main  # Push the changes back to GitHub
